### ISSUE TITLE
Excel function cells

### ISSUE THREAD

**Issue by How45** [How45/Excel_Spending#3]
## Feature
Change cells to Excel math "=()" function to look at other cells
This will create (hopefully a auto updating spreadsheet)

## What?
For coloumns like Total it gets either the cell of above it or cell of different month or different year i.e. month 11 firsts row gets the total of month 10 in the same year file (="10" B3)

## Issues
If new bank is added in a month it needs to update the next month first total as the total changes.
So if Jan 2023 gets a new bank added it needs to update Feb 2023 first row total to the last row of Jan 2023

**Comment by How45** [comment]
## Functionial Issue
User (Me) will probably need excel oooorrrr I have it work with google drive sheets. 
Goog Drive might cause issues, as URL address might be changing ?
##
- Excel: 
    - ='Sheet_name'!Cell_address (When in same workbook)
    - =[Workbook_name]'Sheet_name'!Cell_address (When in different workbook)
- Goog Drive: 
    - ='Sheet_name'!Cell_address (When in same workbook)
    - =IMPORTRANGE("spreadsheet_url","Sheet_name!Cell_address ") (When in different workbook)

**Comment by How45** [comment]
## Task
- [x] Edit get_last_total to retieve that last total of the nearst month of either the same year or a different year
    1. This can be repeated when updating an existing sheet 
- [x] Change to_dataframe to calculate the total based on the total from privous cell i.e. =SUM(D3,E2)

**Comment by How45** [comment]
- [x] Have a function to check if last_total_cell contains a workbook and sheet. In put that in the first row
- [x] Function to update any sheets that might effect the sheet your working on:
    1. Update the last_row_total i.e if 2023.11 is updated with new bank statements update the next sheet or file above it (2024.01) that needs a new pointer to last_row
    2. Or if new sheet is created the sheet above it (in years or month) might need a new first row pointer to total i.e. if sheet 2023.11 is added sheet 2023.12 or 2024.1 needs to get the last_row total of 2023.11

**Comment by How45** [comment]
## Check!
I don't believe we will need cell_value (Lines 140). Believe is only needed when no workbook has existed
