### ISSUE TITLE
Check senarios

### ISSUE THREAD

**Issue by How45** [How45/Excel_Spending#5]
## Issue
- If theres nothing in that month, xlsx is blank. Causing future sheets to have errors
- In Updating_sheet does it update the year infront and being it?
## Task
- [x] Have either something as a placeholder in a blank month or have program check the next month or year that contains a value 
- [x] Check if updating_sheet updates month ahead of it and behind it.

## Issue
- Not getting correct last cell
- Either updating_sheet not working or isn't finding the last_cell correctly
## Task
- [x] Not getting correct last cell
    - Check if its a updating_sheet thing or something else
 
## Issue
- If you add a month e.g. month 6 (2024) but 7 and 8 have already been added. It will reference month 8 on top of the first cell
## Task
- [x] Fix this in the check last row functions

**Comment by How45** [comment]
## Issue
- When running scripy.py, the 2023 bank2 is just using STARTING_VALUE and not referencing privious page
- extra brackets are being added to functions_total again in 2024

## Task
- [x] Fix issue of only using STARTING_VALUE in the earlier sheets
- [x] Fix brackets issue, look if the functions_total are using microsoft excel format

**Comment by How45** [comment]
## Fix 
1. Fix "placeholder in a blank month". After each file is being checked, delete the sheet if its blank
    - Maybe a bit lazy. Could reformat last_cell_amount to accomidate veriable changes like month and year.
3. Fix "if updating_sheet updates month ahead of it and behind it". The issue was inputing new value wasn't working
4. Fix "Not getting correct last cell ". Issue was that I was doing -1, as i was working with google sheets that had blank spaces as the last cell 
5. Fix "month 6 reference month 8". I was getting the last month in the list not numerically last month
6. Fix "2023 bank2 is just using STARTING_VALUE ". Something to do with when getting last_month it was adding 0 to double digit numbers. So it thought there was no privous month
7. Fix "extra brackets". Had to just make the file://dir and sheet into one string. With microsoft excel format. LibreOffice would autofix it for me

**Comment by How45** [comment]
## Re fixed
1. Fix "placeholder in a blank month". Checks if dataframe is empty. if empty don't run tally_account
