### ISSUE TITLE
Add unittesting

### ISSUE THREAD

**Issue by How45** [How45/Excel_Spending#6]
## Task
- [ ] Add proper unittesting. At the end it should meet a condition that will pass the test
- [ ] Create different senarios 
- [ ] At the end of each test delete everything in the finance folder for the next test
- [ ] Clean up files. Add them in folders
